AUG:
  COLOR_JITTER: 0.4
DATA:
  BATCH_SIZE: 132 # means 256 images
  DATASET: "medium_imagenet"
  IMG_SIZE: 64
MODEL:
  NAME: resnet34
  NUM_CLASSES: 200
  DROP_RATE: 0.0
TRAIN:
  EPOCHS: 20
  WARMUP_EPOCHS: 0
  LR: 3e-4
  MIN_LR: 3e-5
  WARMUP_LR: 3e-5
  LR_SCHEDULER:
    NAME: "cosine"
  OPTIMIZER:
    NAME: "adamw"
    EPS: 1e-8
    BETAS: (0.9, 0.999)
    MOMENTUM: 0.9
OUTPUT: "output/log.txt"
SAVE_FREQ: 50 
PRINT_FREQ: 500
